### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by leaicc** [rogerzhu/MNWeeklyCategory#1]
非常感谢你的整理，但是有好多链接可能由于种种原因失效了，希望能去除一下

**Comment by rogerzhu** [comment]
感谢，我也发现了，我准备再过滤一遍，争取下周一之前把现存的都过滤好，去除一下已经失效的。

**Comment by rogerzhu** [comment]
啊 比我预想的晚了一个星期 不过完成了
