### ISSUE TITLE
信息推送

### ISSUE THREAD

**Issue by GooglePeng** [rogerzhu/MNWeeklyCategory#5]
辛苦了，可否创个公众号，方便及时浏览跟新的文章。

**Comment by rogerzhu** [comment]
谢谢，可以试试，让我研究一下先

**Comment by rogerzhu** [comment]
研究了一下，我要做这么一个公众号感觉对于码农周刊的编辑们有点不公，毕竟他们花了人力，我暂时把这个问题关闭，仔细想想怎么样是一个比较合适的方法。
